using System;
using System.Collections.Generic;
using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client.Administration.UI.RoleReqs;

[GenerateTypedNameReferences]
public sealed partial class RoleReqEditorWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _proto = default!;

    public event Action<bool>? OnSetTimers;
    public event Action<bool>? OnSetOverrides;
    public event Action<string, int, TimeSpan>? OnEditTime;
    public event Action<string, int, bool>? OnSetInverted;
    public event Action<string, int>? OnRemove;
    public event Action<string, RoleReqKind, string, TimeSpan, bool>? OnAdd;
    public event Action<string>? OnResetJob;
    public event Action<string>? OnSaveProfile;
    public event Action<string>? OnLoadProfile;
    public event Action<string>? OnDeleteProfile;
    public event Action? OnImport;

    private readonly List<(Label Header, List<RoleReqJobControl> Jobs)> _groups = new();
    private List<string> _profiles = new();
    private bool _updating;

    // Remembered expand state, so the section a job is editing stays open across server-driven rebuilds.
    private readonly HashSet<string> _expandedJobs = new();

    private readonly List<(string Value, string Display)> _roleOptions = new();
    private readonly List<(string Value, string Display)> _deptOptions = new();

    public RoleReqEditorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        BuildOptions();

        TimersCheck.OnToggled += a => { if (!_updating) OnSetTimers?.Invoke(!a.Pressed); };
        OverridesCheck.OnToggled += a => { if (!_updating) OnSetOverrides?.Invoke(a.Pressed); };

        ProfileOption.OnItemSelected += a => ProfileOption.SelectId(a.Id);

        SaveButton.OnPressed += _ =>
        {
            var name = ProfileName.Text.Trim();
            if (name.Length != 0)
                OnSaveProfile?.Invoke(name);
        };
        BackupButton.OnPressed += _ => OnImport?.Invoke();
        LoadButton.OnPressed += _ =>
        {
            if (SelectedProfile() is { } name)
                OnLoadProfile?.Invoke(name);
        };
        DeleteButton.OnPressed += _ =>
        {
            if (SelectedProfile() is { } name)
                OnDeleteProfile?.Invoke(name);
        };

        SearchBar.OnTextChanged += _ => Filter();
    }

    private void BuildOptions()
    {
        foreach (var job in _proto.EnumeratePrototypes<JobPrototype>())
        {
            if (job.SetPreference && !string.IsNullOrEmpty(job.PlayTimeTracker))
                _roleOptions.Add((job.PlayTimeTracker, job.LocalizedName));
        }

        _roleOptions.Sort((a, b) => string.Compare(a.Display, b.Display, StringComparison.OrdinalIgnoreCase));

        foreach (var dept in _proto.EnumeratePrototypes<DepartmentPrototype>())
            _deptOptions.Add((dept.ID, Loc.GetString(dept.Name)));

        _deptOptions.Sort((a, b) => string.Compare(a.Display, b.Display, StringComparison.OrdinalIgnoreCase));
    }

    public void SetState(RoleReqEditorState state)
    {
        _updating = true;
        TimersCheck.Pressed = !state.RoleTimersEnabled;
        OverridesCheck.Pressed = state.OverridesEnabled;
        TimersCheck.Disabled = !state.CanEdit;
        OverridesCheck.Disabled = !state.CanEdit;
        SaveButton.Disabled = !state.CanEdit;
        BackupButton.Disabled = !state.CanEdit;

        _profiles = state.Profiles;
        ProfileOption.Clear();
        if (_profiles.Count == 0)
        {
            ProfileOption.AddItem(Loc.GetString("role-req-editor-profile-none"), 0);
            ProfileOption.SelectId(0);
            LoadButton.Disabled = true;
            DeleteButton.Disabled = true;
        }
        else
        {
            for (var i = 0; i < _profiles.Count; i++)
                ProfileOption.AddItem(_profiles[i], i);
            ProfileOption.SelectId(0);
            LoadButton.Disabled = !state.CanEdit;
            DeleteButton.Disabled = !state.CanEdit;
        }

        _updating = false;

        JobsContainer.RemoveAllChildren();
        _groups.Clear();

        // Group jobs by department the same way the overview / lobby does.
        var grouped = state.Jobs
            .GroupBy(j => j.DepartmentName)
            .OrderBy(g => g.Key == null ? 1 : 0)
            .ThenByDescending(g => g.First().DepartmentWeight)
            .ThenBy(g => g.Key, StringComparer.OrdinalIgnoreCase);

        foreach (var group in grouped)
        {
            var header = new Label
            {
                Text = group.Key ?? Loc.GetString("role-times-department-other"),
                FontColorOverride = Color.FromHex(group.First().DepartmentColor, Color.Gray),
                StyleClasses = { "LabelHeading" },
                Margin = new Thickness(0, 6, 0, 2),
            };
            JobsContainer.AddChild(header);

            var jobs = new List<RoleReqJobControl>();
            foreach (var jobInfo in group)
            {
                var jobId = jobInfo.JobId;
                var control = new RoleReqJobControl(jobInfo, state.CanEdit, _expandedJobs.Contains(jobId),
                    _roleOptions, _deptOptions);
                control.OnEditTime += (idx, t) => OnEditTime?.Invoke(jobId, idx, t);
                control.OnSetInverted += (idx, inv) => OnSetInverted?.Invoke(jobId, idx, inv);
                control.OnRemove += idx => OnRemove?.Invoke(jobId, idx);
                control.OnAdd += (kind, target, t, inv) => OnAdd?.Invoke(jobId, kind, target, t, inv);
                control.OnReset += () => OnResetJob?.Invoke(jobId);
                control.OnExpandChanged += expanded =>
                {
                    if (expanded)
                        _expandedJobs.Add(jobId);
                    else
                        _expandedJobs.Remove(jobId);
                };
                JobsContainer.AddChild(control);
                jobs.Add(control);
            }

            _groups.Add((header, jobs));
        }

        Filter();
    }

    private void Filter()
    {
        var search = SearchBar.Text.Trim();
        foreach (var (header, jobs) in _groups)
        {
            var anyVisible = false;
            foreach (var job in jobs)
            {
                var visible = string.IsNullOrEmpty(search)
                              || job.JobName.Contains(search, StringComparison.OrdinalIgnoreCase)
                              || job.JobId.Contains(search, StringComparison.OrdinalIgnoreCase);
                job.Visible = visible;
                anyVisible |= visible;
            }

            header.Visible = anyVisible;
        }
    }

    private string? SelectedProfile()
    {
        var id = ProfileOption.SelectedId;
        return id >= 0 && id < _profiles.Count ? _profiles[id] : null;
    }
}
