using System;
using System.Collections.Generic;
using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client.Administration.UI.ConnQuality;

[GenerateTypedNameReferences]
public sealed partial class ConnQualityWindow : FancyWindow
{
    private static readonly Color GoodColor = Color.FromHex("#4caf50");
    private static readonly Color OkColor = Color.FromHex("#c8a825");
    private static readonly Color BadColor = Color.FromHex("#e5533d");

    private List<ConnQualityEntry> _entries = new();
    private int _sortColumn = 1; // Ping
    private bool _descending = true;

    public ConnQualityWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetState(ConnQualityEuiState state)
    {
        _entries = state.Entries;
        CountLabel.Text = Loc.GetString("conn-quality-count", ("count", _entries.Count));
        Rebuild();
    }

    private void Rebuild()
    {
        PlayersGrid.RemoveAllChildren();

        AddHeader(0, "conn-quality-col-player");
        AddHeader(1, "conn-quality-col-ping");
        AddHeader(2, "conn-quality-col-status");
        AddHeader(3, "conn-quality-col-connected");

        foreach (var e in Sorted())
        {
            var name = string.IsNullOrEmpty(e.CharacterName)
                ? e.OocName
                : $"{e.CharacterName} ({e.OocName})";
            PlayersGrid.AddChild(new Label { Text = name, HorizontalExpand = true });

            PlayersGrid.AddChild(new Label
            {
                Text = Loc.GetString("conn-quality-ping", ("ping", e.PingMs)),
                Align = Label.AlignMode.Center,
                Margin = new Thickness(8, 0),
                FontColorOverride = e.PingMs switch
                {
                    < 80 => GoodColor,
                    < 150 => OkColor,
                    _ => BadColor,
                },
            });

            PlayersGrid.AddChild(new Label
            {
                Text = e.Status,
                Align = Label.AlignMode.Center,
                Margin = new Thickness(8, 0),
            });

            PlayersGrid.AddChild(new Label
            {
                Text = e.ConnectedFor.ToString(@"hh\:mm\:ss"),
                Align = Label.AlignMode.Center,
                Margin = new Thickness(8, 0),
            });
        }
    }

    private void AddHeader(int col, string loc)
    {
        var arrow = _sortColumn == col ? (_descending ? " v" : " ^") : "";
        var btn = new Button { Text = Loc.GetString(loc) + arrow };
        btn.OnPressed += _ =>
        {
            if (_sortColumn == col)
                _descending = !_descending;
            else
            {
                _sortColumn = col;
                _descending = col != 0;
            }

            Rebuild();
        };
        PlayersGrid.AddChild(btn);
    }

    private IEnumerable<ConnQualityEntry> Sorted()
    {
        IEnumerable<ConnQualityEntry> q = _sortColumn switch
        {
            0 => _entries.OrderBy(e => e.OocName, StringComparer.OrdinalIgnoreCase),
            1 => _entries.OrderBy(e => e.PingMs),
            2 => _entries.OrderBy(e => e.Status, StringComparer.OrdinalIgnoreCase),
            3 => _entries.OrderBy(e => e.ConnectedFor),
            _ => _entries,
        };

        return _descending ? q.Reverse() : q;
    }
}
