using System;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Administration.UI.RoundEndAdConfig;

[GenerateTypedNameReferences]
public sealed partial class RoundEndAdConfigWindow : FancyWindow
{
    public event Action<bool>? OnSetEnabled;
    public event Action<string>? OnSetMessage;

    private bool _updating;
    private bool _saveRequested;

    public RoundEndAdConfigWindow()
    {
        RobustXamlLoader.Load(this);

        EnabledCheck.OnToggled += a =>
        {
            if (!_updating)
                OnSetEnabled?.Invoke(a.Pressed);
        };

        SaveButton.OnPressed += _ =>
        {
            _saveRequested = true;
            OnSetMessage?.Invoke(Rope.Collapse(MessageEdit.TextRope));
        };
    }

    public void SetState(RoundEndAdConfigEuiState state)
    {
        _updating = true;

        EnabledCheck.Pressed = state.Enabled;
        EnabledCheck.Disabled = !state.CanEdit;

        // Don't clobber the text while the admin is typing; only replace when it actually differs.
        if (Rope.Collapse(MessageEdit.TextRope) != state.Message)
            MessageEdit.TextRope = new Rope.Leaf(state.Message);

        MessageEdit.Editable = state.CanEdit;
        SaveButton.Disabled = !state.CanEdit;

        if (_saveRequested)
        {
            SavedLabel.Text = Loc.GetString("round-end-ad-config-saved");
            _saveRequested = false;
        }

        PreviewLabel.Text = state.Message.Replace("\\n", "\n").Trim();

        _updating = false;
    }
}
