using System;
using System.Collections.Generic;
using System.Globalization;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.NewLifeConfig;

[GenerateTypedNameReferences]
public sealed partial class NewLifeConfigWindow : FancyWindow
{
    public event Action<bool>? OnSetEnabled;
    public event Action<bool>? OnSetKeepAntag;
    public event Action<float>? OnSetCooldown;
    public event Action<int>? OnSetMax;
    public event Action<string>? OnSetActiveProfile;
    public event Action<string>? OnCreateProfile;
    public event Action? OnDeleteProfile;
    public event Action<string, bool>? OnSetEvent;

    private List<string> _profiles = new();
    private bool _updating;

    public NewLifeConfigWindow()
    {
        RobustXamlLoader.Load(this);

        EnabledCheck.OnToggled += a =>
        {
            if (!_updating)
                OnSetEnabled?.Invoke(a.Pressed);
        };

        KeepAntagCheck.OnToggled += a =>
        {
            if (!_updating)
                OnSetKeepAntag?.Invoke(a.Pressed);
        };

        CooldownEdit.OnTextEntered += a =>
        {
            if (!_updating && float.TryParse(a.Text, NumberStyles.Float, CultureInfo.InvariantCulture, out var value))
                OnSetCooldown?.Invoke(value);
        };

        MaxEdit.OnTextEntered += a =>
        {
            if (!_updating && int.TryParse(a.Text, out var value))
                OnSetMax?.Invoke(value);
        };

        ProfileOption.OnItemSelected += a =>
        {
            ProfileOption.SelectId(a.Id);
            if (!_updating)
                OnSetActiveProfile?.Invoke(ProfileValue(_profiles, a.Id));
        };
        CreateButton.OnPressed += _ =>
        {
            var name = NameEdit.Text.Trim();
            if (name.Length != 0)
                OnCreateProfile?.Invoke(name);
        };
        DeleteButton.OnPressed += _ => OnDeleteProfile?.Invoke();
    }

    public void SetState(NewLifeConfigEuiState state)
    {
        _updating = true;

        EnabledCheck.Pressed = state.Enabled;
        EnabledCheck.Disabled = !state.CanEdit;

        KeepAntagCheck.Pressed = state.KeepAntag;
        KeepAntagCheck.Disabled = !state.CanEdit;

        CooldownEdit.Text = state.Cooldown.ToString(CultureInfo.InvariantCulture);
        MaxEdit.Text = state.MaxLives.ToString();
        CooldownEdit.Editable = MaxEdit.Editable = state.CanEdit;

        CreateButton.Disabled = DeleteButton.Disabled = !state.CanEdit;

        StatusLabel.Text = state.BlockedNow
            ? Loc.GetString("new-life-config-status-blocked", ("reason", state.BlockedReason))
            : Loc.GetString("new-life-config-status-ok");

        _profiles = state.Profiles;
        PopulateProfiles(ProfileOption, _profiles, state.ActiveProfile);

        _updating = false;

        BuildItems(EventList, state.Events, state.CanEdit, state.ActiveProfile.Length != 0);
    }

    private static string ProfileValue(IReadOnlyList<string> profiles, int id)
    {
        // id 0 is the "(none)" entry (no profile); ids 1.. map to the profile list.
        return id >= 1 && id - 1 < profiles.Count ? profiles[id - 1] : string.Empty;
    }

    private void PopulateProfiles(OptionButton option, List<string> profiles, string active)
    {
        option.Clear();
        option.AddItem(Loc.GetString("new-life-config-none"), 0);
        for (var i = 0; i < profiles.Count; i++)
            option.AddItem(profiles[i], i + 1);

        var selected = 0;
        if (active.Length != 0)
        {
            var idx = profiles.IndexOf(active);
            if (idx >= 0)
                selected = idx + 1;
        }

        option.SelectId(selected);
    }

    private void BuildItems(BoxContainer container, List<NewLifeEventItem> items, bool canEdit, bool hasActive)
    {
        container.RemoveAllChildren();
        foreach (var item in items)
        {
            var check = new CheckBox
            {
                Text = item.Display,
                Pressed = item.Blocked,
                Disabled = !canEdit || !hasActive,
            };
            var id = item.Id;
            check.OnToggled += a => OnSetEvent?.Invoke(id, a.Pressed);
            container.AddChild(check);
        }
    }
}
