using System;
using System.Collections.Generic;
using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.CombatStats;

[GenerateTypedNameReferences]
public sealed partial class CombatStatsWindow : FancyWindow
{
    public event Action? OnRefresh;

    private List<CombatStatEntry> _entries = new();
    private int _sortColumn = 4; // Damage (total)
    private bool _descending = true;

    public CombatStatsWindow()
    {
        RobustXamlLoader.Load(this);
        RefreshButton.OnPressed += _ => OnRefresh?.Invoke();
    }

    public void SetState(CombatStatsEuiState state)
    {
        _entries = state.Entries;
        CountLabel.Text = Loc.GetString("combat-stats-count", ("count", _entries.Count));
        Rebuild();
    }

    private void Rebuild()
    {
        StatsGrid.RemoveAllChildren();

        AddHeader(0, "combat-stats-col-player");
        AddHeader(1, "combat-stats-col-kills-pvp");
        AddHeader(2, "combat-stats-col-kills-total");
        AddHeader(3, "combat-stats-col-damage-pvp");
        AddHeader(4, "combat-stats-col-damage-total");
        AddHeader(5, "combat-stats-col-deaths");

        foreach (var e in Sorted())
        {
            StatsGrid.AddChild(new Label
            {
                Text = $"{e.CharacterName} ({e.OocName})",
                HorizontalExpand = true,
            });
            StatsGrid.AddChild(Num(e.KillsPlayers));
            StatsGrid.AddChild(Num(e.KillsTotal));
            StatsGrid.AddChild(Num((int) MathF.Round(e.DamagePlayers)));
            StatsGrid.AddChild(Num((int) MathF.Round(e.DamageTotal)));
            StatsGrid.AddChild(Num(e.Deaths));
        }
    }

    private void AddHeader(int col, string loc)
    {
        var arrow = _sortColumn == col ? (_descending ? " v" : " ^") : "";
        var btn = new Button
        {
            Text = Loc.GetString(loc) + arrow,
        };
        btn.OnPressed += _ =>
        {
            if (_sortColumn == col)
                _descending = !_descending;
            else
            {
                _sortColumn = col;
                _descending = col != 0; // text column ascending by default, numeric columns descending
            }

            Rebuild();
        };
        StatsGrid.AddChild(btn);
    }

    private IEnumerable<CombatStatEntry> Sorted()
    {
        IEnumerable<CombatStatEntry> q = _sortColumn switch
        {
            0 => _entries.OrderBy(e => e.CharacterName, StringComparer.OrdinalIgnoreCase),
            1 => _entries.OrderBy(e => e.KillsPlayers),
            2 => _entries.OrderBy(e => e.KillsTotal),
            3 => _entries.OrderBy(e => e.DamagePlayers),
            4 => _entries.OrderBy(e => e.DamageTotal),
            5 => _entries.OrderBy(e => e.Deaths),
            _ => _entries,
        };

        return _descending ? q.Reverse() : q;
    }

    private static Label Num(int value)
    {
        return new Label
        {
            Text = value.ToString(),
            Align = Label.AlignMode.Center,
            Margin = new Thickness(8, 0, 8, 0),
        };
    }
}
