using System;
using System.Collections.Generic;
using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.CombatStats;

[GenerateTypedNameReferences]
public sealed partial class CombatStatsWindow : FancyWindow
{
    public event Action? OnRefresh;
    public event Action<int>? OnSelectRound;

    private List<CombatStatEntry> _entries = new();
    private List<int> _rounds = new();
    private int _selectedRound;
    private bool _updatingRounds;
    private int _sortColumn = 4; // Damage (total)
    private bool _descending = true;

    public CombatStatsWindow()
    {
        RobustXamlLoader.Load(this);
        RefreshButton.OnPressed += _ => OnRefresh?.Invoke();

        RoundOption.OnItemSelected += args =>
        {
            RoundOption.SelectId(args.Id);
            if (!_updatingRounds && args.Id < _rounds.Count)
                OnSelectRound?.Invoke(_rounds[args.Id]);
        };

        PrevRoundButton.OnPressed += _ => Step(1); // older round
        NextRoundButton.OnPressed += _ => Step(-1); // newer round
    }

    public void SetState(CombatStatsEuiState state)
    {
        _entries = state.Entries;

        // Populate the round selector (newest first); flag suppresses the selection callback while we set it.
        _updatingRounds = true;
        RoundOption.Clear();
        _rounds = state.AvailableRounds;
        for (var i = 0; i < _rounds.Count; i++)
        {
            var round = _rounds[i];
            var text = round == state.CurrentRound
                ? Loc.GetString("combat-stats-round-current", ("round", round))
                : Loc.GetString("combat-stats-round", ("round", round));
            RoundOption.AddItem(text, i);
            if (round == state.SelectedRound)
                RoundOption.SelectId(i);
        }
        _updatingRounds = false;

        _selectedRound = state.SelectedRound;
        UpdateRoundButtons();

        CountLabel.Text = Loc.GetString("combat-stats-count", ("count", _entries.Count));
        Rebuild();
    }

    private void Step(int delta)
    {
        var idx = _rounds.IndexOf(_selectedRound);
        if (idx < 0)
            return;

        var target = idx + delta;
        if (target < 0 || target >= _rounds.Count)
            return;

        OnSelectRound?.Invoke(_rounds[target]);
    }

    private void UpdateRoundButtons()
    {
        // _rounds is newest-first: the older round is further down the list, the newer one further up.
        var idx = _rounds.IndexOf(_selectedRound);
        PrevRoundButton.Disabled = idx < 0 || idx + 1 >= _rounds.Count;
        NextRoundButton.Disabled = idx <= 0;
    }

    private void Rebuild()
    {
        StatsGrid.RemoveAllChildren();

        AddHeader(0, "combat-stats-col-player");
        AddHeader(1, "combat-stats-col-kills-pvp");
        AddHeader(2, "combat-stats-col-kills-total");
        AddHeader(3, "combat-stats-col-damage-pvp");
        AddHeader(4, "combat-stats-col-damage-total");
        AddHeader(5, "combat-stats-col-deaths");

        foreach (var e in Sorted())
        {
            StatsGrid.AddChild(new Label
            {
                Text = $"{e.CharacterName} ({e.OocName})",
                HorizontalExpand = true,
            });
            StatsGrid.AddChild(Num(e.KillsPlayers));
            StatsGrid.AddChild(Num(e.KillsTotal));
            StatsGrid.AddChild(Num((int) MathF.Round(e.DamagePlayers)));
            StatsGrid.AddChild(Num((int) MathF.Round(e.DamageTotal)));
            StatsGrid.AddChild(Num(e.Deaths));
        }
    }

    private void AddHeader(int col, string loc)
    {
        var arrow = _sortColumn == col ? (_descending ? " v" : " ^") : "";
        var btn = new Button
        {
            Text = Loc.GetString(loc) + arrow,
        };
        btn.OnPressed += _ =>
        {
            if (_sortColumn == col)
                _descending = !_descending;
            else
            {
                _sortColumn = col;
                _descending = col != 0; // text column ascending by default, numeric columns descending
            }

            Rebuild();
        };
        StatsGrid.AddChild(btn);
    }

    private IEnumerable<CombatStatEntry> Sorted()
    {
        IEnumerable<CombatStatEntry> q = _sortColumn switch
        {
            0 => _entries.OrderBy(e => e.CharacterName, StringComparer.OrdinalIgnoreCase),
            1 => _entries.OrderBy(e => e.KillsPlayers),
            2 => _entries.OrderBy(e => e.KillsTotal),
            3 => _entries.OrderBy(e => e.DamagePlayers),
            4 => _entries.OrderBy(e => e.DamageTotal),
            5 => _entries.OrderBy(e => e.Deaths),
            _ => _entries,
        };

        return _descending ? q.Reverse() : q;
    }

    private static Label Num(int value)
    {
        return new Label
        {
            Text = value.ToString(),
            Align = Label.AlignMode.Center,
            Margin = new Thickness(8, 0, 8, 0),
        };
    }
}
