using System;
using System.Collections.Generic;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.RoleTimes;

[GenerateTypedNameReferences]
public sealed partial class RoleTimesWindow : FancyWindow
{
    /// <summary>Raised when the admin commits a new absolute time for a tracker.</summary>
    public event Action<string, TimeSpan>? OnSetTime;

    private readonly List<RoleTimeRow> _rows = new();

    public RoleTimesWindow()
    {
        RobustXamlLoader.Load(this);
        SearchBar.OnTextChanged += _ => Filter();
    }

    public void SetState(RoleTimesEuiState state)
    {
        PlayerLabel.Text = state.Username;
        StatusLabel.Text = Loc.GetString(state.Online ? "role-times-status-online" : "role-times-status-offline");

        RolesContainer.RemoveAllChildren();
        _rows.Clear();

        foreach (var role in state.Roles)
        {
            var row = new RoleTimeRow(role, state.CanEdit);
            var tracker = role.Tracker;
            row.OnSet += time => OnSetTime?.Invoke(tracker, time);
            RolesContainer.AddChild(row);
            _rows.Add(row);
        }

        Filter();
    }

    private void Filter()
    {
        var search = SearchBar.Text.Trim();
        foreach (var row in _rows)
        {
            row.Visible = string.IsNullOrEmpty(search) || row.Matches(search);
        }
    }
}
