using System;
using System.Collections.Generic;
using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client.Administration.UI.RoleTimes;

[GenerateTypedNameReferences]
public sealed partial class RoleTimesWindow : FancyWindow
{
    /// <summary>Raised when the admin commits a new absolute time for a tracker.</summary>
    public event Action<string, TimeSpan>? OnSetTime;

    // Each department group: its header label and the rows under it (for search filtering).
    private readonly List<(Label Header, List<RoleTimeRow> Rows)> _groups = new();

    public RoleTimesWindow()
    {
        RobustXamlLoader.Load(this);
        SearchBar.OnTextChanged += _ => Filter();
    }

    public void SetState(RoleTimesEuiState state)
    {
        PlayerLabel.Text = state.Username;
        StatusLabel.Text = Loc.GetString(state.Online ? "role-times-status-online" : "role-times-status-offline");

        RolesContainer.RemoveAllChildren();
        _groups.Clear();

        // Group by department, ordered the same way the lobby does (weight first), with the
        // department-less catch-all group ("Other") pinned to the end.
        var grouped = state.Roles
            .GroupBy(r => r.DepartmentName)
            .OrderBy(g => g.Key == null ? 1 : 0)
            .ThenByDescending(g => g.First().DepartmentWeight)
            .ThenBy(g => g.Key, StringComparer.OrdinalIgnoreCase);

        foreach (var group in grouped)
        {
            var header = new Label
            {
                Text = group.Key ?? Loc.GetString("role-times-department-other"),
                FontColorOverride = Color.FromHex(group.First().DepartmentColor, Color.Gray),
                StyleClasses = { "LabelHeading" },
                Margin = new Thickness(0, 6, 0, 2),
            };
            RolesContainer.AddChild(header);

            var rows = new List<RoleTimeRow>();
            foreach (var role in group)
            {
                var row = new RoleTimeRow(role, state.CanEdit);
                var tracker = role.Tracker;
                row.OnSet += time => OnSetTime?.Invoke(tracker, time);
                RolesContainer.AddChild(row);
                rows.Add(row);
            }

            _groups.Add((header, rows));
        }

        Filter();
    }

    private void Filter()
    {
        var search = SearchBar.Text.Trim();
        foreach (var (header, rows) in _groups)
        {
            var anyVisible = false;
            foreach (var row in rows)
            {
                var visible = string.IsNullOrEmpty(search) || row.Matches(search);
                row.Visible = visible;
                anyVisible |= visible;
            }

            // Hide the department header when none of its roles match the search.
            header.Visible = anyVisible;
        }
    }
}
