using System;
using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Content.Shared.Database;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client.Administration.UI.Migrations;

[GenerateTypedNameReferences]
public sealed partial class MigrationsWindow : FancyWindow
{
    public event Action<int>? OnApprove;
    public event Action<int>? OnReject;

    /// <summary>Raised on a manual transfer request: (source, target, scope flags).</summary>
    public event Action<string, string, int>? OnManual;

    public MigrationsWindow()
    {
        RobustXamlLoader.Load(this);

        TransferButton.OnPressed += _ => OnManual?.Invoke(SourceEdit.Text, TargetEdit.Text, GatherScope());
    }

    private int GatherScope()
    {
        var scope = MigrationScope.None;
        if (ScopeGameplay.Pressed)
            scope |= MigrationScope.Gameplay;
        if (ScopeWhitelists.Pressed)
            scope |= MigrationScope.Whitelists;
        if (ScopeBans.Pressed)
            scope |= MigrationScope.Bans;
        if (ScopeAdmin.Pressed)
            scope |= MigrationScope.Admin;
        return (int) scope;
    }

    public void SetState(MigrationsEuiState state)
    {
        ResultLabel.Text = state.LastResult ?? string.Empty;

        // Only full admins may migrate admin status; disable (and clear) the checkbox otherwise.
        ScopeAdmin.Disabled = !state.CanMigrateAdmin;
        if (!state.CanMigrateAdmin)
        {
            ScopeAdmin.Pressed = false;
            ScopeAdmin.ToolTip = Loc.GetString("migrations-scope-admin-disabled");
        }

        RowsContainer.RemoveAllChildren();
        // Pending migrations float to the top so they're easy to action; OrderBy is stable so each group
        // keeps the server's newest-first order.
        foreach (var row in state.Rows.OrderByDescending(r => r.Pending))
            RowsContainer.AddChild(MakeRow(row));
    }

    private Control MakeRow(MigrationRow row)
    {
        var panel = new PanelContainer { Margin = new Thickness(0, 2) };
        var box = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(4, 2),
        };
        panel.AddChild(box);

        // Headline: source → target, with full GUIDs on hover. Pending rows are highlighted.
        box.AddChild(new Label
        {
            Text = Loc.GetString("migrations-row-headline",
                ("source", row.SourceName), ("target", row.TargetName)),
            ToolTip = $"{row.Source}\n→ {row.Target}",
            StyleClasses = { "LabelHeading" },
            FontColorOverride = row.Pending ? Color.FromHex("#e3c14e") : Color.White,
        });

        // Meta line: time, auto/manual, status, reason, scope.
        box.AddChild(new Label
        {
            Text = Loc.GetString("migrations-row-meta",
                ("time", row.Time),
                ("kind", Loc.GetString(row.Automatic ? "migrations-kind-auto" : "migrations-kind-manual")),
                ("status", row.StatusText),
                ("reason", row.MatchReason),
                ("scope", row.ScopeText)),
            Modulate = Color.DarkGray,
        });

        if (!string.IsNullOrEmpty(row.Detail))
        {
            box.AddChild(new Label
            {
                Text = Loc.GetString("migrations-row-detail", ("detail", row.Detail)),
                Modulate = Color.DarkGray,
            });
        }

        if (row.Pending)
        {
            var buttons = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(0, 2, 0, 0),
            };
            var id = row.Id;

            var approve = new Button { Text = Loc.GetString("migrations-approve"), StyleClasses = { "Caution" } };
            approve.OnPressed += _ => OnApprove?.Invoke(id);
            buttons.AddChild(approve);

            var reject = new Button { Text = Loc.GetString("migrations-reject"), Margin = new Thickness(4, 0, 0, 0) };
            reject.OnPressed += _ => OnReject?.Invoke(id);
            buttons.AddChild(reject);

            box.AddChild(buttons);
        }

        return panel;
    }
}
