using System;
using System.Collections.Generic;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.VoteConfig;

[GenerateTypedNameReferences]
public sealed partial class VoteConfigWindow : FancyWindow
{
    public event Action<VoteToggle, bool>? OnSetToggle;
    public event Action<bool, string>? OnSetActiveProfile;
    public event Action<bool, string>? OnCreateProfile;
    public event Action<bool>? OnDeleteProfile;
    public event Action<bool, string, bool>? OnSetItem;

    private List<string> _mapProfiles = new();
    private List<string> _presetProfiles = new();
    private bool _updating;

    public VoteConfigWindow()
    {
        RobustXamlLoader.Load(this);

        VoteEnabledCheck.OnToggled += a => Toggle(VoteToggle.Enabled, a.Pressed);
        RestartCheck.OnToggled += a => Toggle(VoteToggle.Restart, a.Pressed);
        PresetCheck.OnToggled += a => Toggle(VoteToggle.Preset, a.Pressed);
        MapCheck.OnToggled += a => Toggle(VoteToggle.Map, a.Pressed);
        VotekickCheck.OnToggled += a => Toggle(VoteToggle.Votekick, a.Pressed);

        MapProfileOption.OnItemSelected += a =>
        {
            MapProfileOption.SelectId(a.Id);
            if (!_updating)
                OnSetActiveProfile?.Invoke(true, ProfileValue(_mapProfiles, a.Id));
        };
        MapCreateButton.OnPressed += _ =>
        {
            var name = MapNameEdit.Text.Trim();
            if (name.Length != 0)
                OnCreateProfile?.Invoke(true, name);
        };
        MapDeleteButton.OnPressed += _ => OnDeleteProfile?.Invoke(true);

        PresetProfileOption.OnItemSelected += a =>
        {
            PresetProfileOption.SelectId(a.Id);
            if (!_updating)
                OnSetActiveProfile?.Invoke(false, ProfileValue(_presetProfiles, a.Id));
        };
        PresetCreateButton.OnPressed += _ =>
        {
            var name = PresetNameEdit.Text.Trim();
            if (name.Length != 0)
                OnCreateProfile?.Invoke(false, name);
        };
        PresetDeleteButton.OnPressed += _ => OnDeleteProfile?.Invoke(false);
    }

    private void Toggle(VoteToggle toggle, bool value)
    {
        if (!_updating)
            OnSetToggle?.Invoke(toggle, value);
    }

    public void SetState(VoteConfigEuiState state)
    {
        _updating = true;

        VoteEnabledCheck.Pressed = state.VoteEnabled;
        RestartCheck.Pressed = state.RestartVote;
        PresetCheck.Pressed = state.PresetVote;
        MapCheck.Pressed = state.MapVote;
        VotekickCheck.Pressed = state.VotekickVote;

        VoteEnabledCheck.Disabled = RestartCheck.Disabled = PresetCheck.Disabled =
            MapCheck.Disabled = VotekickCheck.Disabled = !state.CanEdit;
        MapCreateButton.Disabled = MapDeleteButton.Disabled = !state.CanEdit;
        PresetCreateButton.Disabled = PresetDeleteButton.Disabled = !state.CanEdit;

        _mapProfiles = state.MapProfiles;
        PopulateProfiles(MapProfileOption, _mapProfiles, state.ActiveMapProfile);
        _presetProfiles = state.PresetProfiles;
        PopulateProfiles(PresetProfileOption, _presetProfiles, state.ActivePresetProfile);

        _updating = false;

        BuildItems(MapList, state.Maps, true, state.CanEdit, state.ActiveMapProfile.Length != 0);
        BuildItems(PresetList, state.Presets, false, state.CanEdit, state.ActivePresetProfile.Length != 0);
    }

    private static string ProfileValue(IReadOnlyList<string> profiles, int id)
    {
        // id 0 is the "(default)" entry (no profile); ids 1.. map to the profile list.
        return id >= 1 && id - 1 < profiles.Count ? profiles[id - 1] : string.Empty;
    }

    private void PopulateProfiles(OptionButton option, List<string> profiles, string active)
    {
        option.Clear();
        option.AddItem(Loc.GetString("vote-config-default"), 0);
        for (var i = 0; i < profiles.Count; i++)
            option.AddItem(profiles[i], i + 1);

        var selected = 0;
        if (active.Length != 0)
        {
            var idx = profiles.IndexOf(active);
            if (idx >= 0)
                selected = idx + 1;
        }

        option.SelectId(selected);
    }

    private void BuildItems(BoxContainer container, List<VoteConfigItem> items, bool isMap, bool canEdit, bool hasActive)
    {
        container.RemoveAllChildren();
        foreach (var item in items)
        {
            var check = new CheckBox
            {
                Text = item.Display,
                Pressed = item.Included,
                Disabled = !canEdit || !hasActive,
            };
            var id = item.Id;
            check.OnToggled += a => OnSetItem?.Invoke(isMap, id, a.Pressed);
            container.AddChild(check);
        }
    }
}
