using System;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client.Administration.UI.ServerPerf;

[GenerateTypedNameReferences]
public sealed partial class ServerPerfWindow : FancyWindow
{
    private static readonly Color AvgColor = Color.FromHex("#4caf50");
    private static readonly Color MaxColor = Color.FromHex("#e5533d");
    private static readonly Color CpuColor = Color.FromHex("#4c9ee5");

    private static readonly Color HealthyColor = Color.FromHex("#2c5c2e");
    private static readonly Color StrugglingColor = Color.FromHex("#6b5b1e");
    private static readonly Color OverloadedColor = Color.FromHex("#6b2424");

    public ServerPerfWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetState(ServerPerfEuiState state)
    {
        TpsValue.Text = Loc.GetString("server-perf-tps-value",
            ("actual", state.ActualTps.ToString("0")), ("target", state.TargetTickRate));
        TickValue.Text = Loc.GetString("server-perf-tick-time-value",
            ("avg", state.AvgTickMs.ToString("0.0")),
            ("max", state.MaxTickMs.ToString("0.0")),
            ("budget", state.TickBudgetMs.ToString("0.0")));
        LateValue.Text = state.LateTicksLastMinute.ToString();
        CpuValue.Text = Loc.GetString("server-perf-cpu-value",
            ("cores", state.CpuCoresUsed.ToString("0.00")),
            ("percent", (state.ProcessorCount > 0 ? state.CpuCoresUsed / state.ProcessorCount * 100 : 0).ToString("0.0")));
        MemoryValue.Text = Loc.GetString("server-perf-memory-value",
            ("working", FormatBytes(state.WorkingSetBytes)),
            ("managed", FormatBytes(state.ManagedHeapBytes)));
        GcValue.Text = Loc.GetString("server-perf-gc-value",
            ("gen0", state.Gc0LastMinute), ("gen1", state.Gc1LastMinute), ("gen2", state.Gc2LastMinute),
            ("pause", state.GcPausePercent.ToString("0.00")));
        EntitiesValue.Text = state.EntityCount.ToString("N0");
        PlayersValue.Text = state.PlayerCount.ToString();
        NetValue.Text = Loc.GetString("server-perf-net-value",
            ("up", FormatBytes(state.NetSentBytesPerSec)), ("down", FormatBytes(state.NetRecvBytesPerSec)));
        UptimeValue.Text = state.Uptime.ToString(@"d\d\ hh\:mm\:ss");

        UpdateStatus(state);

        TickGraph.ReferenceLine = state.TickBudgetMs;
        TickGraph.MinScale = state.TickBudgetMs * 2f;
        TickGraph.SetSeries(
            (state.HistoryMaxTickMs, MaxColor),
            (state.HistoryAvgTickMs, AvgColor));
        TickLegend.Text = Loc.GetString("server-perf-graph-tick-legend");

        CpuGraph.ReferenceLine = 1f;
        CpuGraph.MinScale = 2f;
        CpuGraph.SetSeries((state.HistoryCpuCores, CpuColor));
        CpuLegend.Text = Loc.GetString("server-perf-graph-cpu-legend");
    }

    private void UpdateStatus(ServerPerfEuiState state)
    {
        // Overloaded: the server is visibly behind — it processed meaningfully fewer ticks than
        // it should have, or is consistently blowing its budget. Struggling: occasional hitches.
        string status;
        Color color;
        if (state.ActualTps < state.TargetTickRate * 0.9f || state.AvgTickMs > state.TickBudgetMs * 1.1f)
        {
            status = Loc.GetString("server-perf-status-overloaded");
            color = OverloadedColor;
        }
        else if (state.LateTicksLastMinute > 10 || state.MaxTickMs > state.TickBudgetMs * 3f)
        {
            status = Loc.GetString("server-perf-status-struggling");
            color = StrugglingColor;
        }
        else
        {
            status = Loc.GetString("server-perf-status-healthy");
            color = HealthyColor;
        }

        StatusLabel.Text = status;
        StatusPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = color };
    }

    private static string FormatBytes(long bytes)
    {
        return bytes switch
        {
            >= 1024 * 1024 * 1024 => $"{bytes / (1024.0 * 1024 * 1024):0.00} GiB",
            >= 1024 * 1024 => $"{bytes / (1024.0 * 1024):0.0} MiB",
            >= 1024 => $"{bytes / 1024.0:0.0} KiB",
            _ => $"{bytes} B",
        };
    }
}
