using System;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.Administration.UI.AutoRestartConfig;

[GenerateTypedNameReferences]
public sealed partial class AutoRestartConfigWindow : FancyWindow
{
    public event Action<bool>? OnSetEnabled;
    public event Action<string>? OnSetTime;

    private bool _updating;

    // Baseline for the live clock: server local time at the moment the last state arrived,
    // paired with the local wall clock so we can extrapolate between state updates.
    private DateTime _serverNowAtState;
    private DateTime _localAtState;
    private DateTime? _nextRestart;
    private bool _haveState;
    private bool _enabled;
    private bool _pending;

    public AutoRestartConfigWindow()
    {
        RobustXamlLoader.Load(this);

        EnabledCheck.OnToggled += a =>
        {
            if (!_updating)
                OnSetEnabled?.Invoke(a.Pressed);
        };

        TimeEdit.OnTextEntered += a => SubmitTime(a.Text);
        ApplyTimeButton.OnPressed += _ => SubmitTime(TimeEdit.Text);
    }

    private void SubmitTime(string text)
    {
        if (!_updating && text.Trim().Length != 0)
            OnSetTime?.Invoke(text.Trim());
    }

    public void SetState(AutoRestartConfigEuiState state)
    {
        _updating = true;

        EnabledCheck.Pressed = state.Enabled;
        EnabledCheck.Disabled = !state.CanEdit;

        TimeEdit.Text = state.Time;
        TimeEdit.Editable = state.CanEdit;
        ApplyTimeButton.Disabled = !state.CanEdit;

        _serverNowAtState = new DateTime(state.ServerNowTicks);
        _localAtState = DateTime.UtcNow;
        _nextRestart = state.NextRestartTicks != 0 ? new DateTime(state.NextRestartTicks) : null;
        _enabled = state.Enabled;
        _pending = state.Pending;
        _haveState = true;

        _updating = false;

        UpdateClockLabels();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_haveState)
            UpdateClockLabels();
    }

    private void UpdateClockLabels()
    {
        var serverNow = _serverNowAtState + (DateTime.UtcNow - _localAtState);

        ServerTimeLabel.Text = Loc.GetString("auto-restart-config-server-time",
            ("time", serverNow.ToString("HH:mm:ss")));

        if (_pending)
        {
            NextRestartLabel.Text = Loc.GetString("auto-restart-config-next-none");
            StatusLabel.Text = Loc.GetString("auto-restart-config-pending");
            return;
        }

        if (!_enabled || _nextRestart is not { } next)
        {
            NextRestartLabel.Text = Loc.GetString("auto-restart-config-next-none");
            StatusLabel.Text = Loc.GetString("auto-restart-config-disabled");
            return;
        }

        var remaining = next - serverNow;
        if (remaining < TimeSpan.Zero)
            remaining = TimeSpan.Zero;

        NextRestartLabel.Text = Loc.GetString("auto-restart-config-next",
            ("time", next.ToString("HH:mm")),
            ("remaining", FormatRemaining(remaining)));
        StatusLabel.Text = Loc.GetString("auto-restart-config-armed");
    }

    private static string FormatRemaining(TimeSpan remaining)
    {
        return remaining.TotalHours >= 1
            ? $"{(int)remaining.TotalHours}h {remaining.Minutes:D2}m {remaining.Seconds:D2}s"
            : $"{remaining.Minutes}m {remaining.Seconds:D2}s";
    }
}
