using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Content.Shared.TTS;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.TtsConfig;

[GenerateTypedNameReferences]
public sealed partial class TtsConfigWindow : FancyWindow
{
    public event Action<TtsConfigField, string>? OnSet;
    public event Action<string, TtsVoiceGender>? OnSetVoiceGender;
    public event Action<TtsVoiceGender>? OnSetAllGenders;
    public event Action? OnAutoGenders;
    public event Action? OnRefreshSpeakers;
    public event Action<string, string>? OnTest;

    private List<TtsVoiceItem> _voices = new();
    private bool _updating;

    public TtsConfigWindow()
    {
        RobustXamlLoader.Load(this);

        EnabledCheck.OnToggled += a => Set(TtsConfigField.Enabled, a.Pressed.ToString());

        // Commit on Enter and on click-away so typed values aren't lost.
        Bind(UrlEdit, TtsConfigField.ApiUrl);
        Bind(SpeakersUrlEdit, TtsConfigField.SpeakersUrl);
        Bind(ModelsUrlEdit, TtsConfigField.ModelsUrl);
        Bind(TokenEdit, TtsConfigField.ApiToken);
        Bind(SpeedEdit, TtsConfigField.Speed);
        Bind(MaxLengthEdit, TtsConfigField.MaxLength);
        Bind(QueueDelayEdit, TtsConfigField.QueueDelay);

        DefaultSpeakerOption.OnItemSelected += speaker => Set(TtsConfigField.DefaultSpeaker, speaker);
        ModelOption.OnItemSelected += model => Set(TtsConfigField.Model, model);

        RefreshButton.OnPressed += _ => OnRefreshSpeakers?.Invoke();
        AutoGenderButton.OnPressed += _ => OnAutoGenders?.Invoke();

        AllNoneButton.OnPressed += _ => OnSetAllGenders?.Invoke(TtsVoiceGender.None);
        AllMaleButton.OnPressed += _ => OnSetAllGenders?.Invoke(TtsVoiceGender.Male);
        AllFemaleButton.OnPressed += _ => OnSetAllGenders?.Invoke(TtsVoiceGender.Female);

        TestButton.OnPressed += _ =>
        {
            var text = TestTextEdit.Text.Trim();
            if (text.Length != 0)
                OnTest?.Invoke(text, TestSpeakerOption.Selected ?? string.Empty);
        };
    }

    private void Bind(LineEdit edit, TtsConfigField field)
    {
        edit.OnTextEntered += a => Set(field, a.Text);
        edit.OnFocusExit += a => Set(field, a.Text);
    }

    private void Set(TtsConfigField field, string value)
    {
        if (!_updating)
            OnSet?.Invoke(field, value);
    }

    // Don't overwrite a field the user is currently editing (e.g. when an async refresh rebuilds state).
    private static void SetText(LineEdit edit, string value)
    {
        if (!edit.HasKeyboardFocus())
            edit.Text = value;
    }

    public void SetState(TtsConfigEuiState state)
    {
        _updating = true;

        EnabledCheck.Pressed = state.Enabled;
        SetText(UrlEdit, state.ApiUrl);
        SetText(SpeakersUrlEdit, state.SpeakersUrl);
        SetText(ModelsUrlEdit, state.ModelsUrl);
        SetText(TokenEdit, state.ApiToken);
        SetText(SpeedEdit, state.Speed.ToString(CultureInfo.InvariantCulture));
        SetText(MaxLengthEdit, state.MaxLength.ToString(CultureInfo.InvariantCulture));
        SetText(QueueDelayEdit, state.QueueDelay.ToString(CultureInfo.InvariantCulture));

        EnabledCheck.Disabled = !state.CanEdit;
        UrlEdit.Editable = SpeakersUrlEdit.Editable = ModelsUrlEdit.Editable = TokenEdit.Editable = state.CanEdit;
        SpeedEdit.Editable = MaxLengthEdit.Editable = QueueDelayEdit.Editable = state.CanEdit;
        TestButton.Disabled = RefreshButton.Disabled = AutoGenderButton.Disabled = !state.CanEdit;
        AllNoneButton.Disabled = AllMaleButton.Disabled = AllFemaleButton.Disabled = !state.CanEdit;

        StatusLabel.Text = state.Status;

        _voices = state.Voices;
        var names = _voices.Select(v => v.Speaker).ToList();
        DefaultSpeakerOption.SetItems(names);
        DefaultSpeakerOption.SetSelected(state.DefaultSpeaker);
        TestSpeakerOption.SetItems(names);

        ModelOption.SetItems(state.Models);
        ModelOption.SetSelected(state.Model);

        BuildVoiceList(state.CanEdit);

        _updating = false;
    }

    private void BuildVoiceList(bool canEdit)
    {
        VoiceList.RemoveAllChildren();

        string? lastLang = null;
        foreach (var voice in _voices)
        {
            if (voice.Language != lastLang)
            {
                lastLang = voice.Language;
                VoiceList.AddChild(new Label
                {
                    Text = LanguageHeader(voice.Language),
                    StyleClasses = { "LabelKeyText" },
                });
            }

            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
            row.AddChild(new Label { Text = voice.Speaker, MinWidth = 150 });

            var option = new OptionButton { Disabled = !canEdit, HorizontalExpand = true };
            option.AddItem(Loc.GetString("tts-config-gender-none"), (int) TtsVoiceGender.None);
            option.AddItem(Loc.GetString("tts-config-gender-male"), (int) TtsVoiceGender.Male);
            option.AddItem(Loc.GetString("tts-config-gender-female"), (int) TtsVoiceGender.Female);
            option.SelectId((int) voice.Gender);

            var speaker = voice.Speaker;
            option.OnItemSelected += a =>
            {
                option.SelectId(a.Id);
                if (!_updating)
                    OnSetVoiceGender?.Invoke(speaker, (TtsVoiceGender) a.Id);
            };

            row.AddChild(option);
            VoiceList.AddChild(row);
        }
    }

    private static string LanguageHeader(string lang)
    {
        if (string.IsNullOrEmpty(lang))
            return Loc.GetString("tts-config-language-other");

        var key = $"tts-config-language-{lang.ToLowerInvariant()}";
        var localized = Loc.GetString(key);
        // Loc returns the key back when missing; fall back to the upper-cased code.
        return localized == key ? lang.ToUpperInvariant() : localized;
    }
}
