using System;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Maths;

namespace Content.Client.Administration.UI.PlayerRecords;

[GenerateTypedNameReferences]
public sealed partial class PlayerRecordsWindow : FancyWindow
{
    /// <summary>Raised to request a page from the server: (filter, page).</summary>
    public event Action<string, int>? OnRequest;

    // Column header text + pixel width, kept in sync between the header row and the data rows.
    private static readonly (string Loc, float Width)[] Columns =
    {
        ("player-records-col-name", 210),
        ("player-records-col-guid", 360),
        ("player-records-col-first-seen", 150),
        ("player-records-col-last-seen", 150),
        ("player-records-col-address", 120),
        ("player-records-col-playtime", 85),
        ("player-records-col-bans", 60),
        ("player-records-col-status", 240),
    };

    private const float ActionWidth = 70;

    private string _filter = string.Empty;
    private int _page;
    private bool _hasMore;

    public PlayerRecordsWindow()
    {
        RobustXamlLoader.Load(this);

        SearchButton.OnPressed += _ => OnRequest?.Invoke(SearchBar.Text, 0);
        SearchBar.OnTextEntered += _ => OnRequest?.Invoke(SearchBar.Text, 0);
        PrevButton.OnPressed += _ => OnRequest?.Invoke(_filter, Math.Max(0, _page - 1));
        NextButton.OnPressed += _ => OnRequest?.Invoke(_filter, _page + 1);
    }

    public void SetState(PlayerRecordsEuiState state)
    {
        _filter = state.Filter;
        _page = state.Page;
        _hasMore = state.HasMore;

        if (SearchBar.Text != state.Filter)
            SearchBar.Text = state.Filter;

        // Header is part of the scrolled content so columns stay aligned when scrolling horizontally.
        ListContainer.RemoveAllChildren();
        ListContainer.AddChild(MakeHeader());
        foreach (var row in state.Rows)
            ListContainer.AddChild(MakeRow(row));

        PageLabel.Text = Loc.GetString("player-records-page", ("page", _page + 1));
        PrevButton.Disabled = _page <= 0;
        NextButton.Disabled = !_hasMore;
        CountLabel.Text = Loc.GetString("player-records-count", ("count", state.Rows.Count));
    }

    private static BoxContainer MakeHeader()
    {
        var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, Margin = new Thickness(0, 0, 0, 2) };
        foreach (var (loc, width) in Columns)
        {
            row.AddChild(new Label
            {
                Text = Loc.GetString(loc),
                MinWidth = width,
                ClipText = true,
                StyleClasses = { "LabelHeading" },
            });
        }

        row.AddChild(new Control { MinWidth = ActionWidth });
        return row;
    }

    private static BoxContainer MakeRow(PlayerRecordEntry entry)
    {
        var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, Margin = new Thickness(0, 1) };

        var guid = entry.UserId.UserId.ToString();
        // Username and User ID are click-to-copy.
        row.AddChild(CopyCell(entry.UserName, Columns[0].Width, entry.UserName));
        row.AddChild(CopyCell(guid, Columns[1].Width, guid));
        row.AddChild(TextCell(entry.FirstSeen, Columns[2].Width));
        row.AddChild(TextCell(entry.LastSeen, Columns[3].Width));
        row.AddChild(TextCell(entry.Address, Columns[4].Width, entry.Address));
        row.AddChild(TextCell($"{(int) entry.Playtime.TotalHours}h", Columns[5].Width));
        row.AddChild(TextCell(entry.BanCount.ToString(), Columns[6].Width));

        // Migration column: show the actual counterpart, e.g. "← from OldBob" / "→ to NewBob".
        string status;
        Color statusColor;
        if (entry.MigratedFrom != null)
        {
            status = Loc.GetString("player-records-status-into", ("name", entry.MigratedFrom));
            statusColor = Color.FromHex("#7bc86c");
        }
        else if (entry.MigratedTo != null)
        {
            status = Loc.GetString("player-records-status-away", ("name", entry.MigratedTo));
            statusColor = Color.Gray;
        }
        else
        {
            status = string.Empty;
            statusColor = Color.White;
        }

        row.AddChild(new Label
        {
            Text = status,
            MinWidth = Columns[7].Width,
            ClipText = true,
            ToolTip = string.IsNullOrEmpty(status) ? null : status,
            FontColorOverride = statusColor,
        });

        var panel = new Button { Text = Loc.GetString("player-records-panel-button"), MinWidth = ActionWidth };
        panel.OnPressed += _ =>
            IoCManager.Resolve<IClientConsoleHost>().ExecuteCommand($"playerpanel {guid}");
        row.AddChild(panel);

        return row;
    }

    /// <summary>A click-to-copy cell that puts <paramref name="copyValue"/> on the clipboard when pressed.</summary>
    private static Button CopyCell(string text, float width, string copyValue)
    {
        var button = new Button
        {
            Text = text,
            MinWidth = width,
            ClipText = true,
            // Left-align so long values (GUIDs) clip from the end, not symmetrically around the center.
            TextAlign = Label.AlignMode.Left,
            ToolTip = Loc.GetString("player-records-copy-tooltip", ("value", copyValue)),
        };
        button.OnPressed += _ => IoCManager.Resolve<IClipboardManager>().SetText(copyValue);
        return button;
    }

    private static Label TextCell(string text, float width, string? tooltip = null)
    {
        return new Label
        {
            Text = text,
            MinWidth = width,
            ClipText = true,
            ToolTip = tooltip,
        };
    }
}
