using System.Linq;
using System.Numerics;
using Content.Shared.Ghost;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Silicons.StationAi;

[GenerateTypedNameReferences]
public sealed partial class StationAiWarpWindow : DefaultWindow
{
    private List<(string Name, NetEntity Entity)> _warps = new();
    private string _searchText = string.Empty;

    public event Action<NetEntity>? WarpClicked;

    public StationAiWarpWindow()
    {
        RobustXamlLoader.Load(this);
        SearchBar.OnTextChanged += OnSearchTextChanged;
    }

    public void UpdateWarps(IEnumerable<GhostWarp> warps)
    {
        _warps = warps
            .OrderBy(w => w.IsWarpPoint)
            .ThenBy(w => w.DisplayName, Comparer<string>.Create(
                (x, y) => string.Compare(x, y, StringComparison.Ordinal)))
            .Select(w =>
            {
                var name = w.IsWarpPoint
                    ? Loc.GetString("station-ai-warp-window-location", ("name", w.DisplayName))
                    : w.DisplayName;

                return (name, w.Entity);
            })
            .ToList();
    }

    public void Populate()
    {
        ButtonContainer.RemoveAllChildren();
        AddButtons();
    }

    private void AddButtons()
    {
        foreach (var (name, warpTarget) in _warps)
        {
            var currentButtonRef = new Button
            {
                Text = name,
                TextAlign = Label.AlignMode.Right,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                SizeFlagsStretchRatio = 1,
                MinSize = new Vector2(340, 20),
                ClipText = true,
            };

            currentButtonRef.OnPressed += _ => WarpClicked?.Invoke(warpTarget);
            currentButtonRef.Visible = ButtonIsVisible(currentButtonRef);

            ButtonContainer.AddChild(currentButtonRef);
        }
    }

    private bool ButtonIsVisible(Button button)
    {
        return string.IsNullOrEmpty(_searchText) || button.Text == null || button.Text.Contains(_searchText, StringComparison.OrdinalIgnoreCase);
    }

    private void UpdateVisibleButtons()
    {
        foreach (var child in ButtonContainer.Children)
        {
            if (child is Button button)
                button.Visible = ButtonIsVisible(button);
        }
    }

    private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
    {
        _searchText = args.Text;

        UpdateVisibleButtons();
        // Reset scroll bar so they can see the relevant results.
        WarpScroll.SetScrollValue(Vector2.Zero);
    }
}
