using System.Linq;
using System.Numerics;
using Content.Shared.Silicons.StationAi;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Silicons.StationAi;

[GenerateTypedNameReferences]
public sealed partial class StationAiShellWindow : DefaultWindow
{
    private List<StationAiShellData> _shells = new();
    private string _searchText = string.Empty;

    public event Action<NetEntity>? ShellClicked;

    public StationAiShellWindow()
    {
        RobustXamlLoader.Load(this);
        SearchBar.OnTextChanged += OnSearchTextChanged;
    }

    public void UpdateShells(IEnumerable<StationAiShellData> shells)
    {
        _shells = shells
            .OrderBy(s => s.Name, Comparer<string>.Create(
                (x, y) => string.Compare(x, y, StringComparison.Ordinal)))
            .ToList();
    }

    public void Populate()
    {
        ButtonContainer.RemoveAllChildren();
        AddButtons();
    }

    private void AddButtons()
    {
        foreach (var shell in _shells)
        {
            var name = shell.Available
                ? shell.Name
                : Loc.GetString("station-ai-shell-window-in-use", ("name", shell.Name));

            var target = shell.Entity;

            var button = new Button
            {
                Text = name,
                TextAlign = Label.AlignMode.Right,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                SizeFlagsStretchRatio = 1,
                MinSize = new Vector2(340, 20),
                ClipText = true,
                Disabled = !shell.Available,
            };

            if (shell.Available)
                button.OnPressed += _ => ShellClicked?.Invoke(target);

            button.Visible = ButtonIsVisible(button);

            ButtonContainer.AddChild(button);
        }
    }

    private bool ButtonIsVisible(Button button)
    {
        return string.IsNullOrEmpty(_searchText) || button.Text == null || button.Text.Contains(_searchText, StringComparison.OrdinalIgnoreCase);
    }

    private void UpdateVisibleButtons()
    {
        foreach (var child in ButtonContainer.Children)
        {
            if (child is Button button)
                button.Visible = ButtonIsVisible(button);
        }
    }

    private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
    {
        _searchText = args.Text;

        UpdateVisibleButtons();
        ShellScroll.SetScrollValue(Vector2.Zero);
    }
}
