using System;
using System.Collections.Generic;
using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client.Administration.UI.EntityCensus;

[GenerateTypedNameReferences]
public sealed partial class EntityCensusWindow : FancyWindow
{
    private static readonly Color GrowColor = Color.FromHex("#e5533d");
    private static readonly Color ShrinkColor = Color.FromHex("#4caf50");

    [Dependency] private IPrototypeManager _prototypes = default!;

    private List<EntityCensusEntry> _entries = new();
    private bool _minuteAvailable;
    private int _sortColumn = 1; // Count
    private bool _descending = true;

    public EntityCensusWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        FilterEdit.OnTextChanged += _ => Rebuild();
    }

    public void SetState(EntityCensusEuiState state)
    {
        _entries = state.Entries;
        _minuteAvailable = state.MinuteAvailable;
        TotalLabel.Text = Loc.GetString("entity-census-total",
            ("total", state.TotalEntities), ("shown", _entries.Count));
        Rebuild();
    }

    private void Rebuild()
    {
        CensusGrid.RemoveAllChildren();

        AddHeader(0, "entity-census-col-prototype");
        AddHeader(1, "entity-census-col-count");
        AddHeader(2, "entity-census-col-round");
        AddHeader(3, "entity-census-col-minute");

        var filter = FilterEdit.Text.Trim();

        foreach (var e in Sorted())
        {
            var display = e.Prototype;
            if (_prototypes.TryIndex<EntityPrototype>(e.Prototype, out var proto) && proto.Name != e.Prototype)
                display = $"{proto.Name} ({e.Prototype})";

            if (filter.Length > 0 && !display.Contains(filter, StringComparison.OrdinalIgnoreCase))
                continue;

            CensusGrid.AddChild(new Label { Text = display, HorizontalExpand = true, ClipText = true });
            CensusGrid.AddChild(Num(e.Count, null, signed: false));
            CensusGrid.AddChild(Num(e.RoundDelta, DeltaColor(e.RoundDelta), signed: true));
            CensusGrid.AddChild(_minuteAvailable
                ? Num(e.MinuteDelta, DeltaColor(e.MinuteDelta), signed: true)
                : new Label { Text = "—", Align = Label.AlignMode.Center, Margin = new Thickness(8, 0) });
        }
    }

    private static Color? DeltaColor(int delta)
    {
        return delta switch
        {
            > 0 => GrowColor,
            < 0 => ShrinkColor,
            _ => null,
        };
    }

    private void AddHeader(int col, string loc)
    {
        var arrow = _sortColumn == col ? (_descending ? " v" : " ^") : "";
        var btn = new Button { Text = Loc.GetString(loc) + arrow };
        btn.OnPressed += _ =>
        {
            if (_sortColumn == col)
                _descending = !_descending;
            else
            {
                _sortColumn = col;
                _descending = col != 0;
            }

            Rebuild();
        };
        CensusGrid.AddChild(btn);
    }

    private IEnumerable<EntityCensusEntry> Sorted()
    {
        IEnumerable<EntityCensusEntry> q = _sortColumn switch
        {
            0 => _entries.OrderBy(e => e.Prototype, StringComparer.OrdinalIgnoreCase),
            1 => _entries.OrderBy(e => e.Count),
            2 => _entries.OrderBy(e => e.RoundDelta),
            3 => _entries.OrderBy(e => e.MinuteDelta),
            _ => _entries,
        };

        return _descending ? q.Reverse() : q;
    }

    private static Label Num(int value, Color? color, bool signed)
    {
        return new Label
        {
            Text = signed ? value.ToString("+#;-#;0") : value.ToString("N0"),
            Align = Label.AlignMode.Center,
            Margin = new Thickness(8, 0),
            FontColorOverride = color,
        };
    }
}
